server.port: 9005
spring:
  application:
    name: order
jwt:
  secret: ${JWT_SECRET:abcdefghijklmnopqrstuvwxyz123456}
  access-token-validity: 3600000
  refresh-token-validity: 604800000
external:
  deposits:
    base-url: http://localhost:9003
  products:
    base-url: http://localhost:9004
