spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:backend5}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

external:
  deposits:
    base-url: ${USER_SERVICE_HOST}
  payments:
    base-url: ${PAYMENT_SERVICE_URL}
  products:
    base-url: ${PRODUCT_SERVICE_HOST}

logging:
  level:
    org.hibernate.SQL: WARN
