INSERT INTO gateway_whitelist (id, method, path_pattern, description)
VALUES (gen_random_uuid(), 'POST', '/api/v1/auth/login', '로그인'),
       (gen_random_uuid(), 'POST', '/api/v1/auth/reissue', '토큰 재발급'),
       (gen_random_uuid(), 'POST', '/api/v1/users/register', '회원가입'),
       (gen_random_uuid(), 'POST', '/api/v1/users/email-check', '이메일 중복 확인'),
       (gen_random_uuid(), 'POST', '/api/v1/email/**', '이메일 인증'),
       (gen_random_uuid(), 'GET', '/api/v1/products', '상품 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/products/*', '상품 상세 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/products/*/schedules', '상품 일정 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/products/*/availability', '스케줄 예약 가능 여부'),
       (gen_random_uuid(), 'GET', '/api/v1/products/*/reviewList', '상품 리뷰 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/products/*/reviews/*', '리뷰 단건 조회'),
       (gen_random_uuid(), 'GET', '/oauth2/authorization/**', '소셜 로그인 시작'),
       (gen_random_uuid(), 'GET', '/login/oauth2/code/**', '소셜 로그인 콜백');

INSERT INTO gateway_route_policy (id, method, path_pattern, allowed_roles, description)
VALUES (gen_random_uuid(), 'POST', '/api/v1/products', 'SELLER,ADMIN', '상품 등록'),
       (gen_random_uuid(), 'PUT', '/api/v1/products/*', 'SELLER,ADMIN', '상품 수정'),
       (gen_random_uuid(), 'DELETE', '/api/v1/products/*', 'SELLER,ADMIN', '상품 삭제'),
       (gen_random_uuid(), 'POST', '/api/v1/products/*/schedules', 'SELLER,ADMIN', '일정 등록'),
       (gen_random_uuid(), 'PUT', '/api/v1/products/*/schedules/*', 'SELLER,ADMIN', '일정 수정'),
       (gen_random_uuid(), 'DELETE', '/api/v1/products/*/schedules/*', 'SELLER,ADMIN', '일정 삭제'),
       (gen_random_uuid(), 'GET', '/api/v1/settlements', 'SELLER,ADMIN', '정산 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/settlements/ready', 'SELLER,ADMIN', 'READY 정산 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/settlements/*', 'SELLER,ADMIN', '정산 단건 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/settlements/me', 'SELLER,ADMIN', '판매자 정산 목록 조회'),
       (gen_random_uuid(), 'GET', '/api/v1/settlements/me/*/details', 'SELLER,ADMIN', '판매자 정산 상세 항목 조회'),
       (gen_random_uuid(), 'POST', '/api/v1/internal-batch/settlements/calculate', 'ADMIN', '정산 계산 배치 수동 실행'),
       (gen_random_uuid(), 'POST', '/api/v1/internal-batch/settlements/transfer', 'ADMIN', '정산 송금 배치 수동 실행'),
       (gen_random_uuid(), 'GET', '/api/v1/admins/**', 'ADMIN', '어드민 조회'),
       (gen_random_uuid(), 'POST', '/api/v1/admins/**', 'ADMIN', '어드민 등록'),
       (gen_random_uuid(), 'PATCH', '/api/v1/admins/**', 'ADMIN', '어드민 수정'),
       (gen_random_uuid(), 'DELETE', '/api/v1/admins/**', 'ADMIN', '어드민 삭제');
