server:
  port: 9000

spring:
  application:
    name: file

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    aws:
      s3:
        bucket: test-bucket
      region:
        static: ap-northeast-2
      credentials:
        access-key: test-access-key
        secret-key: test-secret-key

jwt:
  secret: 3f2c9a1b7d4e8f6a9c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3 #random
  access-token-validity: 1800000
  refresh-token-validity: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0

logging:
  level:
    jabaclass: DEBUG
    org.springframework.web: DEBUG