server:
  port: 9000

spring:
  application:
    name: file

  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/jabaclass
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # AWS S3 설정
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1800000
  refresh-token-validity: 604800000

# Swagger (SpringDoc) 설정
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs
#    version: OPENAPI_3_0

# 로깅 설정
logging:
  level:
    jabaclass: DEBUG
    org.springframework.web: DEBUG