server:
  port: 9001

spring:
  application:
    name: payment

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

order:
  service:
    url: ${ORDER_SERVICE_URL}

toss:
  secret-key: ${TOSS_SECRET_KEY}