apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ${DOCKERHUB_USERNAME}/chamomile-product:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx512m"

          envFrom:
            - configMapRef:
                name: common-config
                optional: true
            - configMapRef:
                name: product-config
                optional: true
            - secretRef:
                name: common-secret
                optional: true
            - secretRef:
                name: db-secret
                optional: false
            - secretRef:
                name: product-secret
                optional: true

          ports:
            - containerPort: 9004

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9004
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9004
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9004
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 9004
      targetPort: 9004
      protocol: TCP
  type: ClusterIP
