apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ${DOCKERHUB_USERNAME}/chamomile-user:${IMAGE_TAG}
          imagePullPolicy: Always

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms160m -Xmx320m"

          envFrom:
            - configMapRef:
                name: common-config
                optional: true
            - configMapRef:
                name: user-config
                optional: true
            - secretRef:
                name: common-secret
                optional: true
            - secretRef:
                name: db-secret
                optional: false
            - secretRef:
                name: user-secret
                optional: true

          ports:
            - containerPort: 9003

          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              cpu: "300m"
              memory: "640Mi"

          startupProbe:
            httpGet:
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9003
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9003
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 9003
      targetPort: 9003
      protocol: TCP
  type: ClusterIP
